services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  app:
    build: .
    container_name: flask-app
    restart: always
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

  monitor:
    image: nicolargo/glances:latest
    restart: always
    ports:
      - "61208:61208"
    environment:
      - GLANCES_OPT=-w